Добавил базовый класс Контроля Игрока и класс Перемещения Персонажа
DanilaTumanov/GB-project pull request #22
Opened 2018-06-07 22:01 UTC by popuz

...подходит в том числе и для NPC. Создал на сцене Player'a в виде круглешка
close #8

2018-06-07 22:02 UTC, popuz commented
Для NPC подходит конечно только класс CharacterMovement. Но в целом это я так просто накидал, завтра и на выходных буду углубляться в перемещение, смотреть реализации

2018-06-08 08:32 UTC, DanilaTumanov requested changes
Нужна доработка

2018-06-08 08:32 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +            movement = new Vector3(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"), 0);
Не очень хорошее решение.. Постоянно создается новый вектор.. Понимаю, что ты набросал пример, но это может случайно забыться и перекочевать дальше :) давай поправим? Лучше сделать кэшированный вектор, который отвечает за вектор управления и перезаписывать его поля

2018-06-08 08:33 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +            movement = new Vector3(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"), 0);
Плюс избавиться от конфликта, либо решить его

2018-06-08 08:55 UTC, popuz commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +            movement = new Vector3(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"), 0);
Хорошая мысль =)

2018-06-08 09:27 UTC, popuz commented
вроде бы все поправил, проверяй

2018-06-08 10:22 UTC, DanilaTumanov requested changes
Еще немного доработок)

2018-06-08 10:22 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +        private Vector3 movement = Vector3.zero;
Я тебя еще немного помучаю с этой доброской)))) раз уж ты первый, кто более-менее рабочий код закидывает.. Я добавил в wiki на гитхабе требования к кодстайлу https://github.com/DanilaTumanov/GB-project/wiki/Codestyle,
Давай сделаем приватные поля с подчеркиванием? Чтобы в коде сразу было ясно, что это поле закрыто и его никто извне не поменяет

2018-06-08 10:25 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +        private Vector3 movement = Vector3.zero;
И еще по названию ветки - не критично, но лучше начинать название с номера версии - 0.01.10/feature/add_player_ctrl

2018-06-08 13:51 UTC, popuz commented on GB-project/Assets/Scripts/PlayerController/PlayerController.cs
> +        private Vector3 movement = Vector3.zero;
да, с названием уже понял, когда посмотрел как другие делают ))

2018-06-08 14:22 UTC, popuz commented
Ветку уже не стал менять, эту как закроем, пойду на новую

2018-06-08 14:36 UTC, DanilaTumanov approved these changes
Ок

2018-06-08 14:37 UTC, merged