Добавил базовый класс ловушек
DanilaTumanov/GB-project pull request #25
Opened 2018-06-08 18:22 UTC by Martyushevsky

Задача #11

2018-06-08 19:26 UTC, DanilaTumanov requested changes
В целом идея ясна, но хотелось бы обсудить архитектуру

2018-06-08 19:26 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/SceneObjects/BaseTrap.cs
> +        private float _delayBeforeTrapActivation;
Вот тут думаю, что нарушение YAGNI, т.к. геймдизайн ловушки пока не определен, и возможно нам вообще не понадобится таймер... Плюс, даже если так, это должны быть специфические ловушки, к примеру, облако отравленного газа или шипы на земле будут срабатывать без задержки, поэтому в базовом классе такая настройка не вполне уместна..

2018-06-10 11:15 UTC, Martyushevsky commented
closes #11 , closes #26

2018-06-10 18:45 UTC, DanilaTumanov approved these changes
Немного не хватает комментов о назначении классов, но в остальном порядок

2018-06-10 18:45 UTC, merged