Пример архитектуры ИИ.
DanilaTumanov/GB-project pull request #31
Opened 2018-06-09 12:23 UTC by MrTyzer

2018-06-09 12:30 UTC, DanilaTumanov requested changes
Состояния обсудим, остальное по мелочи в комментах

2018-06-09 12:30 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/SceneObjects/Characters/Enemies/AIPatterns.cs
> +namespace GBproject.SceneObjects
Давай сделаем неймспейс GBproject.Controllers.AI, т.к. это из одной оперы

2018-06-09 12:30 UTC, DanilaTumanov commented on GB-project/Assets/Scripts/SceneObjects/Characters/Enemies/AIPatterns.cs
> +    public class AIPatterns
Patterns - множественное число, а класс отвечает за одиночные экземпляры объекта, лучше называть в единственном числе

2018-06-09 12:31 UTC, MrTyzer commented on GB-project/Assets/Scripts/SceneObjects/Characters/Enemies/AIPatterns.cs
> +    public class AIPatterns
Ок щас поправлю

2018-06-09 13:19 UTC, MrTyzer commented
Ща ток забыл поправить названия методов состояний

2018-06-09 15:07 UTC, DanilaTumanov requested changes
Нужно еще раз обсудить архитектуру..

2018-06-13 14:21 UTC, DanilaTumanov approved these changes
Не уверен, что интерфейсы тут необходимы, но давай попробуем, как это заработает :)

2018-06-13 14:21 UTC, merged